#CSharp 


```C#
var whenAllTasks = Task.WhenAll(
new[]{Task.Factory.StartNew(()=>{throw new Exception(); }),
	Task.Factory.StartNew(()=>{throw new Exception(); }) });
try
{
	await whenAllTasks;
}
catch (Exception e)
{
	var singleException = e.Message;
	
	var allExceptions = whenAllTasks.Exception
						.Flattern()
						.InnerExceptions;
}
```
Если мы выполняем коллекцию задач, то стандартный перехват исключения получит только первый `Exception` (`singleException`). Чтобы получить все исключения их нужно доставать вручную(`allExceptions`)